### ISSUE TITLE
체크 항목 영역 오류

### ISSUE THREAD

**Issue by sgshs** [Gaia3D/GeoServerForKaosG#14]
[데이터>레이어>레이어 편집>Data>기본 리소스 정보]
체크 항목(예: '활성화', 'Capabilities 문서, 레이어 미립기 등에서 정보 보이기') 이외의 영역을 클릭하여도 체크가 가능함

**Comment by bjjang-gaia** [comment]
다국어 번역을 대비한 것으로 오류 아님
