### ISSUE TITLE
데이터 원본 이름 저장 기능 오류

### ISSUE THREAD

**Issue by sgshs** [Gaia3D/GeoServerForKaosG#17]
[데이터>저장소>저장소 편집]
'데이터 원본 이름' 항목에 257자 이상 입력 후 '저장' 버튼 클릭 시 제공되는 오류메시지에서 '취소' 버튼을 클릭하여도 입력한 '데이터 원본 이름'이 저장됨

**Comment by sgshs** [comment]
여러번 테스트 진행했으나 취소 버튼 클릭시 저장되지 않고 진행됨

**Comment by sgshs** [comment]
데이터 원본 이름 항목에 입력값을 250자로 제한함.

**Comment by bjjang-gaia** [comment]
TTA 테스트베드에서는 재연됩니다. 해당 상황은 직접 오셔서 확인을 하셔야 될 듯 합니다.(원격 원하시면 원격으로 열어 드릴 수 있습니다)
![image](https://cloud.githubusercontent.com/assets/22909973/20783583/2834a4fe-b7d8-11e6-9cff-e0492d0c5f51.png)

**Comment by sgshs** [comment]
해당 오류는 저장소 글자수가 비정상적으로 길게 입력될 경우 발생하는 예외 사례로 1차 조치에서는 저장소 추가 단계에서 250자 이상의 입력을 차단하였으나 저장소 편집 기능에서도 글자수를 늘려 저장할 소지가 있다 판단되어 편집시에도 마찬가지로 250자 이상의 입력을 차단하고 문제를 해결하였음. 취소 버튼 클릭시 이상작동은 (데이터 원본 이름 글자수가 정상적으로 입력되었을 경우) 정상적으로 작동하는 것으로 판단됨.  추후 취소 기능에서 추적하여 예외 케이스를 별도로 처리하도록 차기 버전에서 패치하겠음.

**Comment by sgshs** [comment]
소스 유실로 인한 이슈 재오픈

**Comment by sgshs** [comment]
오류 페이지를 보여주지 않도록 예외 추가 처리함. 프로세스 자체는 충분한 분석을 통하여 수정 예정
