### ISSUE TITLE
피처 타입 다시 불러오기 기능 오류

### ISSUE THREAD

**Issue by sgshs** [Gaia3D/GeoServerForKaosG#18]
[데이터>레이어>레이어 추가>발행하기>피처 타입 상세정보]
'피처 타입 다시 불러오기' 버튼을 클릭하여도 아무런 동작을 수행하지 않음

**Comment by bjjang-gaia** [comment]
실제 데이터의 구조 변화가 없음으로 동작 안하는 것으로 보일 뿐임.
오류 아님

**Comment by bjjang-gaia** [comment]
TTA: 피처 타입이 없는 경우에는, 확인 메시지를 출력해 주셔야 함

**Comment by bjjang-gaia** [comment]
원본에 변화가 없어서 눌러도 변화가 없음을 다 설명해서 설득하자

**Comment by bjjang-gaia** [comment]
결함리포트에 설명을 보완함
