### ISSUE TITLE
체크박스 표시 미흡

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#22]
[로그인]
[데이터>작업공간>작업공간 추가하기]
'기본 작업공간으로 설정하기' 체크박스가 아래로 표시됨
![image](https://cloud.githubusercontent.com/assets/22909973/20783074/b68bfbf2-b7d4-11e6-809c-15e10823d0d5.png)

**Comment by kimjs4384** [comment]
체크 박스 위치를 "기본 작업공간으로 설정하기" 텍스트 앞으로 이동
![2016-12-02 12 15 40](https://cloud.githubusercontent.com/assets/16930734/20821880/a8a2751a-b889-11e6-9dc7-47dd25bd1fbe.png)
