### ISSUE TITLE
버튼명 표시 미흡

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#23]
[보안>인증>필터 체인]
'서비스 체인 추가', 'HTML 체인 추가' 시 제공되는 버튼 명이 '저장'이 아닌 '닫기'로 잘못 표시됨
![image](https://cloud.githubusercontent.com/assets/22909973/20783067/9f0f8f7a-b7d4-11e6-887a-884aac128b95.png)

**Comment by kimjs4384** [comment]
'저장'으로 수정
