### ISSUE TITLE
필터체인 추가 기능 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#24]
[보안>인증>필터 체인>서비스 체인 추가]
[보안>인증>필터 체인>HTML 체인 추가]
여러 가지 체크 항목 중 '이 체인의 보안 해제' 항목이 체크되어야 '필터 체인' 추가가 가능함

**Comment by sgshs** [comment]
프로세스 전반 점검이 필요한 상태임. 적은 시간으로 확인할 수 있는 규모가 아니기 때문에 우선적으로 "이 체인의 보안 해제" 항목을 필수항목으로 표시함. 내부적으로 분석하여 오류 점검 예정
