### ISSUE TITLE
필수 항목 미표시

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#25]
[데이터>작업공간>작업공간 추가]
[데이터>레이어 그룹>래이어 그룹 추가하기]
[데이터>스타일>스타일 추가하기]
[보안>인증>인증 필터>추가]
[보안>인증>필터 체인>서비스 체인 추가]
[보안>인증>필터 체인>HTML 체인 추가]
[보안>인증>인증 공급자>추가]
[보안>비밀번호>마스터 비밀번호 공급자>추가]
[보안>비밀번호>비밀번호 정책>추가]
[보안>사용자,그룹,역할>서비스>역할 서비스>추가]
[보안>사용자,그룹,역할>사용자/그룹>새로운 사용자 추가하기]
[보안>사용자,그룹,역할>사용자/그룹>새로운 그룹 추가하기]
[보안>사용자,그룹,역할>역할>새로운 역할 추가하기]
[보안>데이터>새로운 룰 추가하기]
[보안>서비스>새로운 룰 추가하기]
프로그램 전반적으로 필수 항목 표시가 되어있지 않음 
 =>1차 결함리포트 15번 결함과 동일

**Comment by sgshs** [comment]
[데이터>작업공간>작업공간 추가] 수정완료
[데이터>레이어 그룹>래이어 그룹 추가하기] 수정완료
[데이터>스타일>스타일 추가하기]  수정완료
[보안>인증>인증 필터>추가] 작업완료
[보안>인증>필터 체인>서비스 체인 추가]작업완료
[보안>인증>필터 체인>HTML 체인 추가]작업완료
[보안>인증>인증 공급자>추가]작업완료
[보안>비밀번호>마스터 비밀번호 공급자>추가]작업완료
[보안>비밀번호>비밀번호 정책>추가]작업완료
[보안>사용자,그룹,역할>서비스>역할 서비스>추가]작업완료
[보안>사용자,그룹,역할>사용자/그룹>새로운 사용자 추가하기]작업완료
[보안>사용자,그룹,역할>사용자/그룹>새로운 그룹 추가하기]작업완료
[보안>사용자,그룹,역할>역할>새로운 역할 추가하기]작업완료
[보안>데이터>새로운 룰 추가하기]작업완료
[보안>서비스>새로운 룰 추가하기]작업완료

**Comment by sgshs** [comment]
소스 유실로 인한 이슈 재오픈

[데이터>작업공간>작업공간 추가] 수정완료
[데이터>레이어 그룹>래이어 그룹 추가하기] 
[데이터>스타일>스타일 추가하기] 
[보안>인증>인증 필터>추가] 
[보안>인증>필터 체인>서비스 체인 추가]
[보안>인증>필터 체인>HTML 체인 추가]
[보안>인증>인증 공급자>추가]
[보안>비밀번호>마스터 비밀번호 공급자>추가]
[보안>비밀번호>비밀번호 정책>추가]작업완료
[보안>사용자,그룹,역할>서비스>역할 서비스>추가]
[보안>사용자,그룹,역할>사용자/그룹>새로운 사용자 추가하기]
[보안>사용자,그룹,역할>사용자/그룹>새로운 그룹 추가하기]작업
[보안>사용자,그룹,역할>역할>새로운 역할 추가하기]작업
[보안>데이터>새로운 룰 추가하기]작업
[보안>서비스>새로운 룰 추가하기]작업

**Comment by jskim412** [comment]
필수 항목 표시 완료

**Comment by kimjs4384** [comment]
필수항목 표시 완료
