### ISSUE TITLE
마스터 비밀번호 추가 기능 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#26]
[보안>비밀번호>마스터 비밀번호 공급자>추가]
'마스터 비밀번호 공급자' 추가 시, "예기치 않은 일이 서버에 발생하였습니다."라는 오류메시지가 제공되고 추가되지 않음
![image](https://cloud.githubusercontent.com/assets/22909973/20783090/d08f828a-b7d4-11e6-969d-643553396f13.png)

**Comment by sgshs** [comment]
12/9 수정 완료 예정

**Comment by sgshs** [comment]
URL 유효성 검사에 의해 발생하는 오류로 기본값을 지정하여 오류가 발생하지 않도록 차단함.
