### ISSUE TITLE
오류 메시지 중목 출력

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#27]
[보안>사용자,그룹,역할>사용자 그룹 서비스>추가>JDBC]
[보안>인증>인증 공급자>추가>JDBC]
'사용자 그룹 서비스' 메뉴에서 발생되는 오류 메시지가 중복으로 출력됨
![image](https://cloud.githubusercontent.com/assets/22909973/20783101/eac966e8-b7d4-11e6-92b4-37cd69e02522.png)

**Comment by sgshs** [comment]
jdbc 부분 view에서 메시지 보여주는 부분이 중복으로 존재함. 주석으로 막고 메시지 중복현상 해결
