### ISSUE TITLE
항목 개수 표시 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#28]
[보안]
실제 추가되어 있는 항목 개수와 '결과'에서 표시되는 항목 개수가 일치하지 않음

**Comment by sgshs** [comment]
#29와 동일한 내용이 중복으로 보고됨. 함께 조치 예정

**Comment by bjjang-gaia** [comment]
완료가 확인되지 않아 다시 오픈함
