### ISSUE TITLE
항목 표시 일관성 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#29]
[보안]
'데이터' 메뉴에서는 관련 작업을 '추가'할 경우 실제 추가된 항목 개수와 '결과'에서 표시되는 항목 개수가 일치하지만 '보안' 메뉴에서는 페이지를 '새로고침' 하지 않으면 항목 개수가 일치하지 않아 메뉴 별로 '항목 표시'의 일관성이 없음
![image](https://cloud.githubusercontent.com/assets/22909973/20783124/0c9e01de-b7d5-11e6-97b1-8c4eac56a998.png)

**Comment by sgshs** [comment]
캡쳐 이미지상에서 #28에서 보고된 바와 같이 항목의 갯수가 일치하지 않음. 함께 확인 진행 예정
