### ISSUE TITLE
불명확한 오류 메시지 제공

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#30]
[보안>사용자,그룹,역할>역할>새로운 역할 추가>역할 속성]
'키' 값을 입력하지 않고 '저장' 버튼 클릭 시 제공되는 오류 메시지가 "속성 이름이 필요합니다."라고 불명확하게 제공됨
![image](https://cloud.githubusercontent.com/assets/22909973/20783132/20e4c420-b7d5-11e6-9574-00e21d3daee4.png)

**Comment by sgshs** [comment]
12/7 수정 완료 예정

**Comment by sgshs** [comment]
수정 완료
![image](https://cloud.githubusercontent.com/assets/20468250/20880038/a5388bc0-bb19-11e6-8472-81a735308788.png)
