### ISSUE TITLE
사용자, 그룹 추가 제목 미제공

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#31]
[보안>사용자,그룹,역할>사용자/그룹]
'사용자', '그룹' 추가 기능을 구분하는 섹션이 제공되어 있지 않음
![image](https://cloud.githubusercontent.com/assets/22909973/20783151/3ec05c02-b7d5-11e6-95a4-8a59ae213512.png)

**Comment by sgshs** [comment]
12/7 수정 완료 예정

**Comment by sgshs** [comment]
섹션 추가함.
추후 다국어 지원을 위한 기능으로 전환 필요함.
