### ISSUE TITLE
불필요한 Edit 버튼 제공

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#32]
[보안>사용자,그룹,역할>사용자/그룹]
[보안>사용자,그룹,역할>역할]
기능을 알 수 없는 불필요한 'Edit' 버튼이 제공됨
![image](https://cloud.githubusercontent.com/assets/22909973/20783158/5fe4a6e0-b7d5-11e6-84ac-c4604617cbab.png)

**Comment by kimjs4384** [comment]
edit 버튼 기능 확인 결과 중복성 확인. 버튼 제거
