### ISSUE TITLE
작업공간 추가하기 기능 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#33]
[데이터>작업공간>작업공간 추가하기]
이름이 같은 작업공간을 중복 추가하기 시, "예기치 않은 일이 서버에 발생하였습니다."라는 메시지가 제공되며 '추가' 기능이 동작하지 않음

**Comment by sgshs** [comment]
#34에서 신규 추가시에도 "예기치 않은 일... " 페이지가 확인된다고 보고되었으나 재연할 수 없었음. 중복 추가시 오류 발생 현상이 신규 추가에 영향을 끼친 것이 아닌가 예상되며 확인중

**Comment by sgshs** [comment]
12/7 수정 완료 예정

**Comment by sgshs** [comment]
#34에서 식별된 이슈로 작업공간 이름과 함께 uri 또한 중복되는 값을 입력할 경우 오류가 발생하고 있음. validate 과정에서 확인해야 함.

**Comment by sgshs** [comment]
오류 발생시 예외 처리를 통하여 작업이 진행될 수 있도록 수정 완료.
하지만 프로세스 자체는 분석이 더 필요할 것임
