### ISSUE TITLE
작업공간 수정 기능 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#34]
[데이터>작업공간]
추가되어 있는 '작업공간'을 수정 후, 수정 전 '작업공간 이름'으로 추가 시, "예기치 않은 일이 서버에 발생하였습니다."라는 오류메시지가 제공되지만 '작업공간' 목록에 추가됨

**Comment by sgshs** [comment]
"qwer" 이름의 작업공간을 생성 후 "qwerqwer"로 변경하고 다시 "qwer" 이라는 이름으로 작업공간을 추가했으나 오류 메시지가 발견되지 않습니다.  #33 의 경우는 현상이 확인되었으므로 이와 연결된 증상일 수 있으므로 함께 증상을 찾아보겠습니다.

**Comment by bjjang-gaia** [comment]
해결이 확인되지 않았으므로 다시 오픈함

**Comment by sgshs** [comment]
12/7 수정 완료 예정

**Comment by sgshs** [comment]
이전 작업공간의 이름으로 추가는 문제되지 않지만 uri가 중복될 경우 #33과 동일하게 오류가 발생하고 있음. 현재 이슈는 문제 없음으로 확인함.
