### ISSUE TITLE
작업공간 이름 수정 오류

### ISSUE THREAD

**Issue by bjjang-gaia** [Gaia3D/GeoServerForKaosG#37]
[데이터>작업공간>수정]
작업공간 추가하기'에서는 '이름'이 250자까지 입력되지만, 작업공간 수정 시에는 '이름'이 255자까지 입력이 가능하여 서로 입력 범위가 상이함

**Comment by bjjang-gaia** [comment]
#8 과 연결됨
모두 250자로 수정하는 것이 바람직

**Comment by sgshs** [comment]
이름 뒤의 글자제한을 250으로 설정하였음.

**Comment by sgshs** [comment]
소스 유실로 인한 이슈 재오픈

**Comment by sgshs** [comment]
12/7 수정 완료 예정

**Comment by sgshs** [comment]
글자수 제한 완료. 250자 초과하는 입력을 받지 못하도록 제한함.
